version: 2
jobs:
  build:
    docker:
      - image: beevelop/ionic
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Update android sdk 
          command: yes | $ANDROID_HOME/tools/bin/sdkmanager --update
      - run:
          name: Accept sdk lincence 
          command: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
      - run:
          name: Building android
          command: ionic cordova build android
      - store_artifacts:
          path: ~/repo/platforms/android/app/build/outputs/apk/debug/app-debug.apk